[build-system]
requires = ["scikit-build-core", "nanobind"]
build-backend = "scikit_build_core.build"

[project]
name = "fem-project"
version = "0.2.0"
description = "FEM project"
dependencies = [
    "numpy",
    "matplotlib",
    "scipy",
    "numba",
    "gmsh",
    "meshpy",
    "pandas",
    "nanobind",
]

[project.optional-dependencies]
dev = [
    "black",
    "autopep8",
    "ipykernel",
    "ipympl",
    "ipywidgets",
    "pybind11-stubgen"
]

[tool.scikit-build]
wheel.packages = ["src"]
#cmake.args = ["--preset", "default", "-DBUILD_MKL_TARGETS=OFF"]
cmake.args = ["-DBUILD_MKL_TARGETS=OFF"]
# cmake.build-type = "Release"

[tool.black]
line-length = 120

[tool.autopep8]
max_line_length = 120
